# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.setWindowModality(QtCore.Qt.NonModal)
        Settings.resize(561, 230)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        Settings.setMinimumSize(QtCore.QSize(561, 230))
        Settings.setMaximumSize(QtCore.QSize(561, 230))
        self.button_save = QtWidgets.QPushButton(Settings)
        self.button_save.setGeometry(QtCore.QRect(450, 180, 101, 41))
        self.button_save.setObjectName("button_save")
        self.gridLayoutWidget = QtWidgets.QWidget(Settings)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 541, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_erotic = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_erotic.setAlignment(QtCore.Qt.AlignCenter)
        self.label_erotic.setObjectName("label_erotic")
        self.gridLayout.addWidget(self.label_erotic, 1, 0, 1, 1)
        self.lineEdit_erotic = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_erotic.setReadOnly(True)
        self.lineEdit_erotic.setObjectName("lineEdit_erotic")
        self.gridLayout.addWidget(self.lineEdit_erotic, 1, 1, 1, 1)
        self.label_art = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_art.setMinimumSize(QtCore.QSize(60, 0))
        self.label_art.setAlignment(QtCore.Qt.AlignCenter)
        self.label_art.setObjectName("label_art")
        self.gridLayout.addWidget(self.label_art, 0, 0, 1, 1)
        self.label_porn = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_porn.setAlignment(QtCore.Qt.AlignCenter)
        self.label_porn.setObjectName("label_porn")
        self.gridLayout.addWidget(self.label_porn, 2, 0, 1, 1)
        self.button_open_art = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_open_art.setObjectName("button_open_art")
        self.gridLayout.addWidget(self.button_open_art, 0, 2, 1, 1)
        self.lineEdit_art = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_art.setEnabled(True)
        self.lineEdit_art.setReadOnly(True)
        self.lineEdit_art.setObjectName("lineEdit_art")
        self.gridLayout.addWidget(self.lineEdit_art, 0, 1, 1, 1)
        self.button_open_erotic = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_open_erotic.setObjectName("button_open_erotic")
        self.gridLayout.addWidget(self.button_open_erotic, 1, 2, 1, 1)
        self.button_open_porn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_open_porn.setObjectName("button_open_porn")
        self.gridLayout.addWidget(self.button_open_porn, 2, 2, 1, 1)
        self.lineEdit_porn = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_porn.setReadOnly(True)
        self.lineEdit_porn.setClearButtonEnabled(False)
        self.lineEdit_porn.setObjectName("lineEdit_porn")
        self.gridLayout.addWidget(self.lineEdit_porn, 2, 1, 1, 1)
        self.label_trash = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_trash.setAlignment(QtCore.Qt.AlignCenter)
        self.label_trash.setObjectName("label_trash")
        self.gridLayout.addWidget(self.label_trash, 3, 0, 1, 1)
        self.lineEdit_trash = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_trash.setReadOnly(True)
        self.lineEdit_trash.setClearButtonEnabled(False)
        self.lineEdit_trash.setObjectName("lineEdit_trash")
        self.gridLayout.addWidget(self.lineEdit_trash, 3, 1, 1, 1)
        self.button_open_trash = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_open_trash.setObjectName("button_open_trash")
        self.gridLayout.addWidget(self.button_open_trash, 3, 2, 1, 1)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.button_save.setText(_translate("Settings", "Save"))
        self.label_erotic.setText(_translate("Settings", "Erotics path"))
        self.label_art.setText(_translate("Settings", "Arts path"))
        self.label_porn.setText(_translate("Settings", "Porns path"))
        self.button_open_art.setText(_translate("Settings", "Open..."))
        self.button_open_erotic.setText(_translate("Settings", "Open..."))
        self.button_open_porn.setText(_translate("Settings", "Open..."))
        self.label_trash.setText(_translate("Settings", "Trash path"))
        self.button_open_trash.setText(_translate("Settings", "Open..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QWidget()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())
