# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1302, 884)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 64))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(64, 64))
        self.frame_toggle.setStyleSheet("background-color: rgb(35, 0, 0);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle.sizePolicy().hasHeightForWidth())
        self.btn_toggle.setSizePolicy(sizePolicy)
        self.btn_toggle.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(35, 0, 0);\n"
"border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 255);\n"
"background-color: rgb(76, 0, 0);\n"
"}")
        self.btn_toggle.setText("")
        self.btn_toggle.setObjectName("btn_toggle")
        self.verticalLayout_2.addWidget(self.btn_toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 64))
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(64, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(64, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 0, 0);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 3, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_left_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_left_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menus.setObjectName("frame_left_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_left_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_menu_songs = QtWidgets.QPushButton(self.frame_left_menus)
        self.btn_menu_songs.setMinimumSize(QtCore.QSize(0, 64))
        self.btn_menu_songs.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(35, 0, 0);\n"
"border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 255);\n"
"background-color: rgb(76, 0, 0);\n"
"}")
        self.btn_menu_songs.setObjectName("btn_menu_songs")
        self.verticalLayout_4.addWidget(self.btn_menu_songs)
        self.btn_menu_playlists = QtWidgets.QPushButton(self.frame_left_menus)
        self.btn_menu_playlists.setMinimumSize(QtCore.QSize(0, 64))
        self.btn_menu_playlists.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(35, 0, 0);\n"
"border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 255);\n"
"background-color: rgb(76, 0, 0);\n"
"}")
        self.btn_menu_playlists.setObjectName("btn_menu_playlists")
        self.verticalLayout_4.addWidget(self.btn_menu_playlists)
        self.btn_menu_downloads = QtWidgets.QPushButton(self.frame_left_menus)
        self.btn_menu_downloads.setMinimumSize(QtCore.QSize(0, 64))
        self.btn_menu_downloads.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(35, 0, 0);\n"
"border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 255);\n"
"background-color: rgb(76, 0, 0);\n"
"}")
        self.btn_menu_downloads.setObjectName("btn_menu_downloads")
        self.verticalLayout_4.addWidget(self.btn_menu_downloads)
        self.verticalLayout_3.addWidget(self.frame_left_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pages_Widget = QtWidgets.QStackedWidget(self.frame_pages)
        self.pages_Widget.setObjectName("pages_Widget")
        self.page_songs = QtWidgets.QWidget()
        self.page_songs.setObjectName("page_songs")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_songs)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget = QtWidgets.QTableWidget(self.page_songs)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"selection-color: rgb(35, 0, 0)\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_6.addWidget(self.tableWidget)
        self.pages_Widget.addWidget(self.page_songs)
        self.page_playlists = QtWidgets.QWidget()
        self.page_playlists.setObjectName("page_playlists")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_playlists)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_playlists_top = QtWidgets.QFrame(self.page_playlists)
        self.frame_playlists_top.setMinimumSize(QtCore.QSize(0, 55))
        self.frame_playlists_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_playlists_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_playlists_top.setObjectName("frame_playlists_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_playlists_top)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_createPlaylist = QtWidgets.QPushButton(self.frame_playlists_top)
        self.btn_createPlaylist.setMinimumSize(QtCore.QSize(128, 48))
        self.btn_createPlaylist.setMaximumSize(QtCore.QSize(128, 48))
        self.btn_createPlaylist.setStyleSheet("background-color: lightgrey")
        self.btn_createPlaylist.setObjectName("btn_createPlaylist")
        self.horizontalLayout_3.addWidget(self.btn_createPlaylist)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_deletePlaylist = QtWidgets.QPushButton(self.frame_playlists_top)
        self.btn_deletePlaylist.setMinimumSize(QtCore.QSize(128, 48))
        self.btn_deletePlaylist.setMaximumSize(QtCore.QSize(128, 48))
        self.btn_deletePlaylist.setStyleSheet("background-color: lightgrey")
        self.btn_deletePlaylist.setObjectName("btn_deletePlaylist")
        self.horizontalLayout_3.addWidget(self.btn_deletePlaylist)
        self.verticalLayout_7.addWidget(self.frame_playlists_top)
        self.table_playlists = QtWidgets.QTableWidget(self.page_playlists)
        self.table_playlists.setObjectName("table_playlists")
        self.table_playlists.setColumnCount(3)
        self.table_playlists.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_playlists.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_playlists.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_playlists.setHorizontalHeaderItem(2, item)
        self.verticalLayout_7.addWidget(self.table_playlists)
        self.pages_Widget.addWidget(self.page_playlists)
        self.page_downloads = QtWidgets.QWidget()
        self.page_downloads.setObjectName("page_downloads")
        self.pages_Widget.addWidget(self.page_downloads)
        self.verticalLayout_5.addWidget(self.pages_Widget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_menu_songs.setText(_translate("MainWindow", "Songs"))
        self.btn_menu_playlists.setText(_translate("MainWindow", "Playlists"))
        self.btn_menu_downloads.setText(_translate("MainWindow", "Downloads"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Duration"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Author"))
        self.btn_createPlaylist.setText(_translate("MainWindow", "Create playlist"))
        self.btn_deletePlaylist.setText(_translate("MainWindow", "Delete playlist"))
        item = self.table_playlists.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table_playlists.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Song count"))
        item = self.table_playlists.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Duration"))
