# Generated by Django 4.0.5 on 2022-10-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('title', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=300, null=True)),
                ('isbn', models.CharField(db_collation='utf8_general_ci', db_column='ISBN', max_length=17, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=306, null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=15000, null=True)),
                ('link', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=300, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
    ]
