# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangePath.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditPathsWidget(object):
    def setupUi(self, EditPathsWidget):
        EditPathsWidget.setObjectName("EditPathsWidget")
        EditPathsWidget.resize(417, 417)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditPathsWidget)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.path_list = QtWidgets.QListWidget(EditPathsWidget)
        self.path_list.setObjectName("path_list")
        self.verticalLayout.addWidget(self.path_list)
        self.add_delete_path_frame = QtWidgets.QFrame(EditPathsWidget)
        self.add_delete_path_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.add_delete_path_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_delete_path_frame.setObjectName("add_delete_path_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.add_delete_path_frame)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_addPath = QtWidgets.QPushButton(self.add_delete_path_frame)
        self.btn_addPath.setObjectName("btn_addPath")
        self.verticalLayout_2.addWidget(self.btn_addPath)
        self.btn_deletePath = QtWidgets.QPushButton(self.add_delete_path_frame)
        self.btn_deletePath.setObjectName("btn_deletePath")
        self.verticalLayout_2.addWidget(self.btn_deletePath)
        self.verticalLayout.addWidget(self.add_delete_path_frame)
        self.cancel_save_path_frame = QtWidgets.QFrame(EditPathsWidget)
        self.cancel_save_path_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cancel_save_path_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cancel_save_path_frame.setObjectName("cancel_save_path_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.cancel_save_path_frame)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_OKPathChange = QtWidgets.QPushButton(self.cancel_save_path_frame)
        self.btn_OKPathChange.setObjectName("btn_OKPathChange")
        self.horizontalLayout.addWidget(self.btn_OKPathChange)
        self.verticalLayout.addWidget(self.cancel_save_path_frame)

        self.retranslateUi(EditPathsWidget)
        QtCore.QMetaObject.connectSlotsByName(EditPathsWidget)

    def retranslateUi(self, EditPathsWidget):
        _translate = QtCore.QCoreApplication.translate
        EditPathsWidget.setWindowTitle(_translate("EditPathsWidget", "Form"))
        self.btn_addPath.setText(_translate("EditPathsWidget", "Add"))
        self.btn_deletePath.setText(_translate("EditPathsWidget", "Delete"))
        self.btn_OKPathChange.setText(_translate("EditPathsWidget", "OK"))
