# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewPlaylist.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Playlist_add_form(object):
    def setupUi(self, Playlist_add_form):
        Playlist_add_form.setObjectName("Playlist_add_form")
        Playlist_add_form.resize(741, 586)
        self.verticalLayout = QtWidgets.QVBoxLayout(Playlist_add_form)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.new_playlist_name_line = QtWidgets.QLineEdit(Playlist_add_form)
        self.new_playlist_name_line.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.new_playlist_name_line.setFont(font)
        self.new_playlist_name_line.setObjectName("new_playlist_name_line")
        self.verticalLayout.addWidget(self.new_playlist_name_line)
        self.frame = QtWidgets.QFrame(Playlist_add_form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.songlist = QtWidgets.QTableWidget(self.frame)
        self.songlist.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.songlist.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.songlist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.songlist.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.songlist.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.songlist.setShowGrid(False)
        self.songlist.setGridStyle(QtCore.Qt.NoPen)
        self.songlist.setObjectName("songlist")
        self.songlist.setColumnCount(2)
        self.songlist.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.songlist.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.songlist.setHorizontalHeaderItem(1, item)
        self.songlist.horizontalHeader().setCascadingSectionResizes(True)
        self.songlist.horizontalHeader().setMinimumSectionSize(275)
        self.songlist.horizontalHeader().setSortIndicatorShown(True)
        self.songlist.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.songlist)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_cancel = QtWidgets.QPushButton(self.frame_2)
        self.btn_cancel.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_cancel.setObjectName("btn_cancel")
        self.verticalLayout_2.addWidget(self.btn_cancel)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.btn_save = QtWidgets.QPushButton(self.frame_2)
        self.btn_save.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout_2.addWidget(self.btn_save)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Playlist_add_form)
        QtCore.QMetaObject.connectSlotsByName(Playlist_add_form)

    def retranslateUi(self, Playlist_add_form):
        _translate = QtCore.QCoreApplication.translate
        Playlist_add_form.setWindowTitle(_translate("Playlist_add_form", "Form"))
        self.new_playlist_name_line.setPlaceholderText(_translate("Playlist_add_form", "New playlist name"))
        self.songlist.setSortingEnabled(True)
        item = self.songlist.horizontalHeaderItem(0)
        item.setText(_translate("Playlist_add_form", "Name"))
        item = self.songlist.horizontalHeaderItem(1)
        item.setText(_translate("Playlist_add_form", "Author"))
        self.btn_cancel.setText(_translate("Playlist_add_form", "Cancel"))
        self.btn_save.setText(_translate("Playlist_add_form", "Save"))
