# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Playlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(468, 617)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.playlist_name_lable = QtWidgets.QLabel(Form)
        self.playlist_name_lable.setMinimumSize(QtCore.QSize(0, 50))
        self.playlist_name_lable.setText("")
        self.playlist_name_lable.setObjectName("playlist_name_lable")
        self.verticalLayout.addWidget(self.playlist_name_lable)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_2.setObjectName("listWidget_2")
        self.horizontalLayout_2.addWidget(self.listWidget_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_play_2 = QtWidgets.QPushButton(self.frame_5)
        self.btn_play_2.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_play_2.setObjectName("btn_play_2")
        self.verticalLayout_5.addWidget(self.btn_play_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.btn_shuffle_2 = QtWidgets.QPushButton(self.frame_5)
        self.btn_shuffle_2.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_shuffle_2.setObjectName("btn_shuffle_2")
        self.verticalLayout_5.addWidget(self.btn_shuffle_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.btn_back_2 = QtWidgets.QPushButton(self.frame_5)
        self.btn_back_2.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_back_2.setObjectName("btn_back_2")
        self.verticalLayout_5.addWidget(self.btn_back_2)
        self.verticalLayout_4.addWidget(self.frame_5, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_play_2.setText(_translate("Form", "Play"))
        self.btn_shuffle_2.setText(_translate("Form", "Shuffle"))
        self.btn_back_2.setText(_translate("Form", "Back"))
